Skip building stack_frame.cc and eh_return.c with PNaCl sjlj.
They use __builtin_dwarf_cfa, which turns into
llvm.eh.dwarf.cfa, which is disallowed in stable bitcode.

Also, the way the SJLJ environment was constructed is
different from the rest of the EH testing environments.
Namely, it does not do AddBiasForPNaCl and does not filter
out -pedantic so things fail even earlier while building:

http://build.chromium.org/p/tryserver.nacl/builders/nacl-precise_64-newlib-x86_32-pnacl/builds/422/steps/build_all/logs/stdio

tests/toolchain/stack_frame.cc:52:2: error: "unknown arch"
 ^
 1 error generated.
scons: *** [scons-out/nacl-x86-32-pnacl-pexe-clang/obj/tests/toolchain/stack_frame_sjlj.o] Error 1

That blocks a TOOL_REVISIONS roll:
https://codereview.chromium.org/68993002/

BUG=https://code.google.com/p/nativeclient/issues/detail?id=3696
R=mseaborn@chromium.org

Review URL: https://codereview.chromium.org/68633004

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@12373 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2