Fix failure on PNaCl FYI bots introduced by r12210: run "SDK" install step
The "llvm-test-suite" step on the PNaCl x86-32 FYI bots was failing with:

ERROR: sdk dir does not seem to exist
ERROR: have you run 'pnacl/build.sh sdk newlib' ?

Fix this by running the "sdk" step explicitly.

BUG= https://code.google.com/p/nativeclient/issues/detail?id=3696
TEST= none

Review URL: https://codereview.chromium.org/26278004

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@12216 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2